import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import red from '@/styles/Test.module.css'
import Header from '@/components/Header'
import Form from '@/components/Form'
import React, { useState } from 'react';
import Text from '@/components/Text'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  const [numbersOfParagraphs, setNumbersOfParagraphs] = useState<string>('');

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    
    console.log(numbersOfParagraphs);

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Form handleSubmit={handleSubmit} numbersOfParagraphs={numbersOfParagraphs} setNumbersOfParagraphs={setNumbersOfParagraphs}/>
        <Text txt='paragraph'/>
      </main>
    </>
  )
}
